In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Window / Flatmap exercises

Task 1

In [ ]:
data = np.arange(0,100)
ds1 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=None,
    sequence_length=10,
    sequence_stride=1,
    sampling_rate=1,
    batch_size=None
)
for item in ds1.take(3):
  print(f"{item} {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[ 1  2  3  4  5  6  7  8  9 10] (10,)
**************************************************
[ 2  3  4  5  6  7  8  9 10 11] (10,)
**************************************************


In [ ]:
ds2 = tf.data.Dataset.range(0, 100).window(size=10, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(10))
for item in ds2.take(3):
  print(f"{item} {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[ 1  2  3  4  5  6  7  8  9 10] (10,)
**************************************************
[ 2  3  4  5  6  7  8  9 10 11] (10,)
**************************************************


Task 2

In [ ]:
data = np.arange(0,100)
ds1 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=None,
    sequence_length=10,
    sequence_stride=1,
    sampling_rate=1,
    batch_size=3
)
for item in ds1.take(3):
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]] (3, 10)
**************************************************
[[ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]] (3, 10)
**************************************************
[[ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]] (3, 10)
**************************************************


In [ ]:
ds2 = tf.data.Dataset.range(0, 100).window(size=10, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(10)).window(size=3).flat_map(lambda ds: ds.batch(3))
for item in ds2.take(3):
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]] (3, 10)
**************************************************
[[ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]] (3, 10)
**************************************************
[[ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]] (3, 10)
**************************************************


Task 3

In [ ]:
data = np.arange(0,100)
ds1 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=None,
    sequence_length=10,
    sequence_stride=5,
    sampling_rate=1,
    batch_size=3
)
for item in ds1.take(3):
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************


In [ ]:
ds2 = tf.data.Dataset.range(0, 100).window(size=10, shift=5, drop_remainder=True).flat_map(lambda ds: ds.batch(10)).window(size=3).flat_map(lambda ds: ds.batch(3))
for item in ds2.take(3):
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************


Task 4

In [ ]:
data = np.arange(0,100)
ds1 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=data[10:],
    sequence_length=10,
    sequence_stride=5,
    sampling_rate=1,
    batch_size=None
)
for item, label in ds1.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************


In [ ]:
ds2 = tf.data.Dataset.range(0, 100).window(size=11, shift=5, drop_remainder=True).flat_map(lambda ds: ds.batch(11)).map(lambda x: (x[:-1], x[-1]))
for item, label in ds2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************


Task 5

In [ ]:
ds2 = tf.data.Dataset.range(0, 100).window(size=7, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(7)).map(lambda x: (x[:-2], x[-2:]))
for item, label in ds2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [5 6] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [6 7] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [7 8] and has shape (5,)
**************************************************


Task 6

In [ ]:
ds2_v2 = (tf.data.Dataset.range(0, 100)
          .window(size=7, shift=1, drop_remainder=True)
          .flat_map(lambda ds: ds.batch(7))
          .map(lambda x: (x[:-2], x[-2:]))
          .shuffle(buffer_size=10_000, seed=42)
          .batch(10)
)
for item, label in ds2_v2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[[15 16 17 18 19]
 [72 73 74 75 76]
 [10 11 12 13 14]
 [67 68 69 70 71]
 [ 3  4  5  6  7]
 [56 57 58 59 60]
 [46 47 48 49 50]
 [77 78 79 80 81]
 [76 77 78 79 80]
 [49 50 51 52 53]] maps to [[20 21]
 [77 78]
 [15 16]
 [72 73]
 [ 8  9]
 [61 62]
 [51 52]
 [82 83]
 [81 82]
 [54 55]] and has shape (10, 5)
**************************************************
[[54 55 56 57 58]
 [63 64 65 66 67]
 [19 20 21 22 23]
 [ 5  6  7  8  9]
 [12 13 14 15 16]
 [33 34 35 36 37]
 [71 72 73 74 75]
 [87 88 89 90 91]
 [14 15 16 17 18]
 [48 49 50 51 52]] maps to [[59 60]
 [68 69]
 [24 25]
 [10 11]
 [17 18]
 [38 39]
 [76 77]
 [92 93]
 [19 20]
 [53 54]] and has shape (10, 5)
**************************************************
[[20 21 22 23 24]
 [89 90 91 92 93]
 [42 43 44 45 46]
 [17 18 19 20 21]
 [32 33 34 35 36]
 [58 59 60 61 62]
 [68 69 70 71 72]
 [59 60 61 62 63]
 [93 94 95 96 97]
 [91 92 93 94 95]] maps to [[25 26]
 [94 95]
 [47 48]
 [22 23]
 [37 38]
 [63 64]
 [73 74]
 [64 65]
 [98 99]
 [96 97]] and has shape 

In [ ]:
ds2 = (tf.data.Dataset.range(0, 100)
          .window(size=7, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(7))
          .shuffle(buffer_size=10_000, seed=42)
          .window(size=10, drop_remainder=True).flat_map(lambda ds: ds.batch(10))
          .map(lambda x: (x[:, :-2], x[:, -2:]))
      )
for item, label in ds2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[[15 16 17 18 19]
 [72 73 74 75 76]
 [10 11 12 13 14]
 [67 68 69 70 71]
 [ 3  4  5  6  7]
 [56 57 58 59 60]
 [46 47 48 49 50]
 [77 78 79 80 81]
 [76 77 78 79 80]
 [49 50 51 52 53]] maps to [[20 21]
 [77 78]
 [15 16]
 [72 73]
 [ 8  9]
 [61 62]
 [51 52]
 [82 83]
 [81 82]
 [54 55]] and has shape (10, 5)
**************************************************
[[54 55 56 57 58]
 [63 64 65 66 67]
 [19 20 21 22 23]
 [ 5  6  7  8  9]
 [12 13 14 15 16]
 [33 34 35 36 37]
 [71 72 73 74 75]
 [87 88 89 90 91]
 [14 15 16 17 18]
 [48 49 50 51 52]] maps to [[59 60]
 [68 69]
 [24 25]
 [10 11]
 [17 18]
 [38 39]
 [76 77]
 [92 93]
 [19 20]
 [53 54]] and has shape (10, 5)
**************************************************
[[20 21 22 23 24]
 [89 90 91 92 93]
 [42 43 44 45 46]
 [17 18 19 20 21]
 [32 33 34 35 36]
 [58 59 60 61 62]
 [68 69 70 71 72]
 [59 60 61 62 63]
 [93 94 95 96 97]
 [91 92 93 94 95]] maps to [[25 26]
 [94 95]
 [47 48]
 [22 23]
 [37 38]
 [63 64]
 [73 74]
 [64 65]
 [98 99]
 [96 97]] and has shape 

Task 7

Dit is gewoon een test

In [17]:
ds_test = tf.data.Dataset.range(0, 100).window(size=10, shift=1, drop_remainder=True).flat_map(lambda x: x.batch(10)).window(size=5, shift=1, drop_remainder=True) #.flat_map(lambda x: x.batch(5))

for ds in ds_test.take(3):
  print(ds)
  for item in ds:
    print(item)
  print()

<_VariantDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int64, name=None)>
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64)
tf.Tensor([ 2  3  4  5  6  7  8  9 10 11], shape=(10,), dtype=int64)
tf.Tensor([ 3  4  5  6  7  8  9 10 11 12], shape=(10,), dtype=int64)
tf.Tensor([ 4  5  6  7  8  9 10 11 12 13], shape=(10,), dtype=int64)

<_VariantDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int64, name=None)>
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64)
tf.Tensor([ 2  3  4  5  6  7  8  9 10 11], shape=(10,), dtype=int64)
tf.Tensor([ 3  4  5  6  7  8  9 10 11 12], shape=(10,), dtype=int64)
tf.Tensor([ 4  5  6  7  8  9 10 11 12 13], shape=(10,), dtype=int64)
tf.Tensor([ 5  6  7  8  9 10 11 12 13 14], shape=(10,), dtype=int64)

<_VariantDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int64, name=None)>
tf.Tensor([ 2  3  4  5  6  7  8  9 10 11], shape=(10,), dtype=int6

In [ ]:
ds2 = (tf.data.Dataset.range(0, 100)
        .window(size=5, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(5))
        .window(size=2, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(2))
        # .map(lambda ds: (ds[0], ds[1])) # map is hier zelfs niet nodig
)
for item, label in ds2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [1 2 3 4 5] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [2 3 4 5 6] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [3 4 5 6 7] and has shape (5,)
**************************************************


In [ ]:
ds2_v2_windows = (tf.data.Dataset.range(100).window(
    size=2,
    shift=1,
    drop_remainder=True)
  .flat_map(lambda ds : ds.batch(2))
  .window(
      size=5,
      shift=1,
      drop_remainder=True)
  .flat_map(lambda ds: ds.batch(5))
  .map(lambda S : (S[:,0], S[:,-1]))
)
for item, label in ds2_v2_windows.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [1 2 3 4 5] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [2 3 4 5 6] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [3 4 5 6 7] and has shape (5,)
**************************************************


Task 8

In [ ]:
ds2 = (tf.data.Dataset.range(0, 100)
        .window(size=5, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(5))
        .window(size=5, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(5))
        .map(lambda x: (x[0], x[:, 1:]))
)
for item, label in ds2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [[ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]] and has shape (5,)
**************************************************


In [ ]:
ds2_v2 = (tf.data.Dataset.range(0, 100)
        .window(size=4, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(4))
        .window(size=5, shift=1, drop_remainder=True).flat_map(lambda ds: ds.batch(5))
        .map(lambda x: (x[:,0], x[:, 1:]))
)
for item, label in ds2_v2.take(3):
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [[3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]] and has shape (5,)
**************************************************
