In [ ]:
import numpy as np
import tensorflow as tf

# Task 1

In [ ]:
data = np.arange(0,100)

ds1 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=None,
    sequence_length=10,
    sequence_stride=10,
    batch_size=None
    )

In [ ]:
for item in ds1:
  print(f"{item} {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] (10,)
**************************************************
[50 51 52 53 54 55 56 57 58 59] (10,)
**************************************************
[60 61 62 63 64 65 66 67 68 69] (10,)
**************************************************
[70 71 72 73 74 75 76 77 78 79] (10,)
**************************************************
[80 81 82 83 84 85 86 87 88 89] (10,)
**************************************************
[90 91 92 93 94 95 96 97 98 99] (10,)
**************************************************


In [ ]:
ds1_window = tf.data.Dataset.range(100).window(size=10).flat_map(lambda x: x.batch(10))

In [ ]:
for item in ds1_window:
  print(f"{item} {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] (10,)
**************************************************
[50 51 52 53 54 55 56 57 58 59] (10,)
**************************************************
[60 61 62 63 64 65 66 67 68 69] (10,)
**************************************************
[70 71 72 73 74 75 76 77 78 79] (10,)
**************************************************
[80 81 82 83 84 85 86 87 88 89] (10,)
**************************************************
[90 91 92 93 94 95 96 97 98 99] (10,)
**************************************************


# Task 2

In [ ]:
ds2 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=None,
    sequence_length=10,
    sequence_stride=10,
    batch_size=3
    )

In [ ]:
for item in ds2:
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************


In [ ]:
ds2_window = tf.data.Dataset.range(100).window(size=10).flat_map(lambda x: x.batch(10)).batch(3)

In [ ]:
for item in ds2_window:
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************


# Task 3

In [ ]:
ds3 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=None,
    sequence_length=10,
    sequence_stride=5,
    batch_size=3
    )

In [ ]:
for item in ds3:
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************
[[45 46 47 48 49 50 51 52 53 54]
 [50 51 52 53 54 55 56 57 58 59]
 [55 56 57 58 59 60 61 62 63 64]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [65 66 67 68 69 70 71 72 73 74]
 [70 71 72 73 74 75 76 77 78 79]] (3, 10)
**************************************************
[[75 76 77 78 79 80 81 82 83 84]
 [80 81 82 83 84 85 86 87 88 89]
 [85 86 87 88 89 90 91 92 93 94]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
****

In [ ]:
ds3_window = tf.data.Dataset.range(100).window(size=10, shift=5).flat_map(lambda x: x.batch(10)).batch(3, drop_remainder=True)

In [ ]:
for item in ds3_window:
  print(f"{item} {item.shape}")
  print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************
[[45 46 47 48 49 50 51 52 53 54]
 [50 51 52 53 54 55 56 57 58 59]
 [55 56 57 58 59 60 61 62 63 64]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [65 66 67 68 69 70 71 72 73 74]
 [70 71 72 73 74 75 76 77 78 79]] (3, 10)
**************************************************
[[75 76 77 78 79 80 81 82 83 84]
 [80 81 82 83 84 85 86 87 88 89]
 [85 86 87 88 89 90 91 92 93 94]] (3, 10)
**************************************************


# Task 4

In [ ]:
ds4 = tf.keras.utils.timeseries_dataset_from_array(
    data=data,
    targets=data[10:],
    sequence_length=10,
    sequence_stride=5,
    batch_size=None
    )

In [ ]:
for item, label in ds4:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************
[15 16 17 18 19 20 21 22 23 24] maps to 25 and has shape (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] maps to 30 and has shape (10,)
**************************************************
[25 26 27 28 29 30 31 32 33 34] maps to 35 and has shape (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] maps to 40 and has shape (10,)
**************************************************
[35 36 37 38 39 40 41 42 43 44] maps to 45 and has shape (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] maps to 50 and has shape (10,)
***********************************

In [ ]:
ds4_window = tf.data.Dataset.range(100).window(size=10, shift=5, drop_remainder=True).flat_map(lambda x: x.batch(10)).map(lambda x: (x, (x[-1] + 1)))

In [ ]:
for item, label in ds4_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************
[15 16 17 18 19 20 21 22 23 24] maps to 25 and has shape (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] maps to 30 and has shape (10,)
**************************************************
[25 26 27 28 29 30 31 32 33 34] maps to 35 and has shape (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] maps to 40 and has shape (10,)
**************************************************
[35 36 37 38 39 40 41 42 43 44] maps to 45 and has shape (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] maps to 50 and has shape (10,)
***********************************

# Task 5

In [ ]:
ds5_window = tf.data.Dataset.range(100).window(
    size=5,
    shift=1,
    drop_remainder=True
).flat_map(lambda x: x.batch(5, drop_remainder=True)).map(lambda x: (x, [(x[-1] + 1), (x[-1] + 2)]))

In [ ]:
for item, label in ds5_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [5 6] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [6 7] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [7 8] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [8 9] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [ 9 10] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [10 11] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [11 12] and has shape (5,)
**************************************************
[ 7  8  9 10 11] maps to [12 13] and has shape (5,)
**************************************************
[ 8  9 10 11 12] maps to [13 14] and has shape (5,)
**************************************************
[ 9 10 11 12 13] maps to [14 15] and has shape (5,)
**************************************************
[10 11 1

# Task 6

In [ ]:
ds6_window = tf.data.Dataset.range(100).window(
    size=5,
    shift=1,
    drop_remainder=True
).flat_map(lambda x: x.batch(5, drop_remainder=True)).map(lambda x: (x, [(x[-1] + 1), (x[-1] + 2)])).shuffle(buffer_size=10_000, seed=42).batch(10)

In [ ]:
for item, label in ds6_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[[ 9 10 11 12 13]
 [92 93 94 95 96]
 [70 71 72 73 74]
 [85 86 87 88 89]
 [61 62 63 64 65]
 [32 33 34 35 36]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [16 17 18 19 20]
 [51 52 53 54 55]] maps to [[14 15]
 [97 98]
 [75 76]
 [90 91]
 [66 67]
 [37 38]
 [10 11]
 [ 5  6]
 [21 22]
 [56 57]] and has shape (10, 5)
**************************************************
[[ 2  3  4  5  6]
 [76 77 78 79 80]
 [ 3  4  5  6  7]
 [14 15 16 17 18]
 [87 88 89 90 91]
 [ 8  9 10 11 12]
 [47 48 49 50 51]
 [30 31 32 33 34]
 [89 90 91 92 93]
 [12 13 14 15 16]] maps to [[ 7  8]
 [81 82]
 [ 8  9]
 [19 20]
 [92 93]
 [13 14]
 [52 53]
 [35 36]
 [94 95]
 [17 18]] and has shape (10, 5)
**************************************************
[[40 41 42 43 44]
 [19 20 21 22 23]
 [52 53 54 55 56]
 [68 69 70 71 72]
 [24 25 26 27 28]
 [83 84 85 86 87]
 [23 24 25 26 27]
 [86 87 88 89 90]
 [15 16 17 18 19]
 [66 67 68 69 70]] maps to [[45 46]
 [24 25]
 [57 58]
 [73 74]
 [29 30]
 [88 89]
 [28 29]
 [91 92]
 [20 21]
 [71 72]] and has shape 

# Task 7

In [ ]:
ds7_window = tf.data.Dataset.range(100).window(
    size=5,
    shift=1,
    drop_remainder=True
).flat_map(lambda x: x.batch(5)).window(size=2, shift=1, drop_remainder=True).flat_map(lambda x: x.batch(5)).map(lambda x: (x[0], x[1]))

Cause: could not parse the source code of <function <lambda> at 0x7c092dc2f7f0>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda x: (x[0], x[1])

Match 1:
lambda x: x.batch(5)

Match 2:
lambda x: x.batch(5)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: could not parse the source code of <function <lambda> at 0x7c092dc2f7f0>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names. The matching definitions were:
Match 0:
lambda x: (x[0], x[1])

Match 1:
lambda x: x.batch(5)

Match 2:
lambda x: x.batch(5)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [ ]:
for item, label in ds7_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [1 2 3 4 5] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [2 3 4 5 6] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [3 4 5 6 7] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [4 5 6 7 8] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [5 6 7 8 9] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [ 6  7  8  9 10] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [ 7  8  9 10 11] and has shape (5,)
**************************************************
[ 7  8  9 10 11] maps to [ 8  9 10 11 12] and has shape (5,)
**************************************************
[ 8  9 10 11 12] maps to [ 9 10 11 12 13] and has shape (5,)
**************************************************
[ 9 10 11 12 13] maps to [10 11 12 13 14] and h

# Task 8

In [ ]:
ds8_window = tf.data.Dataset.range(100).window(size=4, shift=1, drop_remainder=True).flat_map(lambda x: x.batch(5)).window(size=5, drop_remainder=True).flat_map(lambda x: x.batch(5)).map(lambda x: (x[:, 0], x[:, 1:]))

In [ ]:
for item, label in ds8_window:
  print(f"{item} maps to {label} and has shape {item.shape}")
  print("*"*50)

[0 1 2 3 4] maps to [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]] and has shape (5,)
**************************************************
[10 11 12 13 14] maps to [[11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]] and has shape (5,)
**************************************************
[15 16 17 18 19] maps to [[16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]] and has shape (5,)
**************************************************
[20 21 22 23 24] maps to [[21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]] and has shape (5,)
**************************************************
[25 26 27 28 29] maps to [[26 27 28]
 [27 28 29]
 [28 29 30]
 [29 30 31]
 [30 31 32]] and has shape (5,)
**************************************************
[30 31 32 33 34] maps to [[31 32 33]
 [32 33 34]
 [33 34 35]
 [34 35 36]
 [35 36 37]] and

# Jena Climate Data

In [ ]:
import tensorflow as tf
import shutil
import pandas as pd
import numpy as np

## Step 1

In [ ]:
data = tf.keras.utils.get_file(origin="https://s3.amazonaws.com/keras-datasets/jena_climate_2009_2016.csv.zip")

13565642/13565642 [==============================] - 1s 0us/step


In [ ]:
data_unzip = shutil.unpack_archive(data)

In [ ]:
df = pd.read_csv("./jena_climate_2009_2016.csv")
df.head()

Date Time  p (mbar)  T (degC)  Tpot (K)  Tdew (degC)  rh (%)  \
0  01.01.2009 00:10:00    996.52     -8.02    265.40        -8.90    93.3   
1  01.01.2009 00:20:00    996.57     -8.41    265.01        -9.28    93.4   
2  01.01.2009 00:30:00    996.53     -8.51    264.91        -9.31    93.9   
3  01.01.2009 00:40:00    996.51     -8.31    265.12        -9.07    94.2   
4  01.01.2009 00:50:00    996.51     -8.27    265.15        -9.04    94.1   

   VPmax (mbar)  VPact (mbar)  VPdef (mbar)  sh (g/kg)  H2OC (mmol/mol)  \
0          3.33          3.11          0.22       1.94             3.12   
1          3.23          3.02          0.21       1.89             3.03   
2          3.21          3.01          0.20       1.88             3.02   
3          3.26          3.07          0.19       1.92             3.08   
4          3.27          3.08          0.19       1.92             3.09   

   rho (g/m**3)  wv (m/s)  max. wv (m/s)  wd (deg)  
0       1307.75      1.03           1.75     152.3  
1       1309.80      0.72           1.50     136.1  
2       1310.24      0.19           0.63     171.6  
3       1309.19      0.34           0.50     198.0  
4       1309.00      0.32           0.63     214.3

In [ ]:
temperature = np.array(df['T (degC)'])
raw_data = np.array(df.drop(['Date Time'], axis=1))

In [ ]:
df.shape

(420451, 15)

In [ ]:
temperature.shape, raw_data.shape

((420451,), (420451, 14))

## Step 2

In [ ]:
perc_50 = df.shape[0] // 2
perc_25 = df.shape[0] // 4

In [ ]:
X_train = raw_data[:perc_50]
y_train = temperature[:perc_50]

X_train.shape, y_train.shape

((210225, 14), (210225,))

In [ ]:
X_test = raw_data[-perc_25:]
y_test = temperature[-perc_25:]

X_test.shape, y_test.shape

((105112, 14), (105112,))

In [ ]:
X_val = raw_data[perc_50: -perc_25]
y_val = temperature[perc_50: -perc_25]

X_val.shape, y_val.shape

((105114, 14), (105114,))

### Normalisatie

In [ ]:
mu = np.mean(X_train, axis=0)
sigma = np.std(X_train, axis=0)

In [ ]:
X_train_norm = ((X_train - mu) / sigma)
X_test_norm = ((X_test - mu) / sigma)
X_val_norm = ((X_val - mu) / sigma)

In [ ]:
X_train[0][1]

-8.02

In [ ]:
X_train_norm[0][1]

-1.9206401523830878

In [ ]:
(X_train_norm[0][1] * sigma[1]) + mu[1]

-8.02

# create dataset

In [ ]:
def create_ds(data, label, train=False, bs=256):
  ds = tf.keras.utils.timeseries_dataset_from_array(
      data=data,
      targets=label[(120 * 6 + 23 * 6):],
      sequence_length=120,
      sampling_rate=6,
      batch_size=bs,
      shuffle=train
      )
  return ds

In [ ]:
train_ds = create_ds(X_train_norm, y_train, train=True)
test_ds = create_ds(X_test_norm, y_test, train=False)
val_ds = create_ds(X_val_norm, y_test, train=False)

In [ ]:
my_check_ds = create_ds(
    data=df.values[:1000, 0],
    label=df.values[:1000, 0],
    train=False,
    bs=1
)

for features, target in my_check_ds.take(2):
  print(f"{features} maps to {target}")
  print("*"*50)

# Step 3: Establish a Common Sense Baseline

In [ ]:
def compute_naive_mae(dataset):
  total = 0
  for f, l in dataset:
    f = (f * sigma) + mu
    for idx, i in enumerate(f):
      total += abs(i[:, 1] - l[idx])
  return total/dataset.cardinality().numpy()

# Step 4: Establish a Non-Sequence Baseline

In [ ]:
for i, j in train_ds.take(1):
  print(i.shape)

(256, 120, 14)


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation="relu", input_shape=(120, 14)),
    tf.keras.layers.Dense(14, activation="softmax")
])

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 16)                240       
                                                                 
 dense_7 (Dense)             (None, 14)                238       
                                                                 
Total params: 478 (1.87 KB)
Trainable params: 478 (1.87 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(optimizer=tf.keras.optimizers.RMSprop(), metrics=["mean_absolute_errror"], loss="sparse_categorical_crossentropy")

In [ ]:
checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath='/tmp/checkpoint', save_best_only=True)

In [ ]:
model.fit(train_ds, validation_data=val_ds, callbacks=[checkpoint], epochs=10)